name: Java CI with Maven - Test and package

on: [pull_request]

# Workflow
jobs:
  build:
    
    name: build
    runs-on: ubuntu-latest
    if: false

    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4

        with:
          distribution: 'corretto'
          java-version: '21'

      - name : Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=$(echo ${{ github.repository }} | sed 's-/-_-') \
          -Dsonar.token=$SONAR_TOKEN



