name: Documentions JAVADOC


on:
  pull_request:
    types: [closed, merged]

# Workflow
jobs:
  build:
    
    name: build
    runs-on: ubuntu-latest

    steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Java
            uses: actions/setup-java@v4
            with:
              distribution: 'corretto'
              java-version: '21'

          - name: Build with Maven JavaDoc
            run: |
              mvn -B javadoc:javadoc

          - name: Deploy
            uses: peaceiris/actions-gh-pages@v4
            with:
              github_token: ${{ secrets.DOC_TOKEN }}
              publish_dir: ./target/site/apidocs



